runAndPrintExceptions(const boost::function<void ()> &func) {
	runAndPrintExceptions(func, true);
}